from .piece import Piece
from ..colors import Colors


class Bishop(Piece):
    def __init__(self, color):
        """Create a bishop with a certain color.
        :param color: The color of a chess piece
        :type color: Color
        """
        super().__init__(color)
        self.white_unicode_val = '\u2657'
        self.black_unicode_val = '\u265d'

    def generate_possible_moves(self, board, old_x, old_y):
        """Generates all possible moves that a bishop can make. It does not
        check to see if the move will leave a player checked. So not every
        move generated by this function is actually a valid move.
        :param board: The chess board
        :type board: Board
        :param old_x: The x location the piece is starting at
        :type old_x: Int
        :param old_y: The y location the piece is starting at
        :type old_y: Int
        :returns: List of all possible moves
        :rtype: List
        """
        possible_moves = set()
        delta_x = [-1, 1]
        delta_y = [-1, 1]

        # The bishop can move diagonally in any direction. This loop will loop
        # over all four diagonals and then traverse the diagonal until it
        # hits another piece or is out of bounds.
        for dx in delta_x:
            for dy in delta_y:
                for diag in range(1, 8):
                    pos_x = dx * diag + old_x
                    pos_y = dy * diag + old_y
                    if board.move_on_board(pos_x, pos_y):
                        if board.board[pos_y][pos_x].piece is None:
                            possible_moves.add((pos_x, pos_y))
                        elif board.board[pos_y][pos_x].piece.color != \
                                self.color:
                            possible_moves.add((pos_x, pos_y))
                            break
                        elif board.board[pos_y][pos_x].piece.color == \
                                self.color:
                            break
                    else:
                        break

        return possible_moves
