from .piece import Piece
from ..colors import Colors


class Rook(Piece):
    def __init__(self, color):
        """Create a rook with a certain color.
        :param color: The color of a chess piece
        :type color: Color
        """
        super().__init__(color)
        self.white_unicode_val = '\u2656'
        self.black_unicode_val = '\u265C'

    def generate_possible_moves(self, board, old_x, old_y):
        """Generates all possible moves that a rook can make. It does not
        check to see if the move will leave a player checked. So not every
        move generated by this function is actually a valid move.
        :param board: The chess board
        :type board: Board
        :param old_x: The x location the piece is starting at
        :type old_x: Int
        :param old_y: The y location the piece is starting at
        :type old_y: Int
        :returns: List of all possible moves
        :rtype: List
        """
        possible_moves = set()

        # The rook can move left, right, forwards, and backwards.
        delta_x = [-1, 1]
        delta_y = [-1, 1]

        # Try going right/left until the rook hits another
        # piece.
        for dx in delta_x:
            for x in range(1, 8):
                pos_x = dx * x + old_x
                if board.move_on_board(pos_x, old_y):
                    if board.board[old_y][pos_x].piece is None:
                        possible_moves.add((pos_x, old_y))
                    elif board.board[old_y][pos_x].piece.color != self.color:
                        possible_moves.add((pos_x, old_y))
                        break
                    else:
                        break

                # The move would place the rook off the board
                else:
                    break

        # Try going forwards/backwards until the rook hits another
        # piece.
        for dy in delta_y:
            for y in range(1, 8):
                pos_y = dy * y + old_y
                if board.move_on_board(old_x, pos_y):
                    if board.board[pos_y][old_x].piece is None:
                        possible_moves.add((old_x, pos_y))
                    elif board.board[pos_y][old_x].piece.color != self.color:
                        possible_moves.add((old_x, pos_y))
                        break
                    else:
                        break

                # Move would place the rook off of the board
                else:
                    break

        return possible_moves
